import {winning,pool,moves,chooseMove,play} from './engine-removal.js?v=lock1';
const $=id=>document.getElementById(id);let board=Array(9).fill(0),turn=1,selected=null,ended=false,winLines=[],latest=-1,round=0,timer,worker;let rights=[true,true],locks=[null,null],removing=false,passNote="";let last='Die KI überlegt ihren ersten Zug.';
function render(){
 $('board').replaceChildren(...board.map((n,i)=>{const el=document.createElement('button');el.className='cell'+(n?(n%2?' odd':' even'):'')+(winLines.some(l=>l.includes(i))?' win':'')+(latest===i?' latest':'');el.disabled=turn===1||ended||(removing?!(n&&n%2===1):!!n);if(removing&&n%2===1&&!ended)el.classList.add('removable');el.setAttribute('aria-label',`Zeile ${Math.floor(i/3)+1}, Spalte ${i%3+1}: ${n||'frei'}`);el.innerHTML=`<span class="position">${i+1}</span>${n||'·'}`;el.onclick=()=>removing?removeHuman(i):placeHuman(i,selected);return el}));
 for(const [id,p]of [['human',0],['ai',1]]){$(id).replaceChildren(...pool(p).map(n=>{const used=board.includes(n),blocked=locks[p]===n,el=document.createElement(p?'span':'button');el.className='number'+(used?' used':'')+(blocked?' blocked':'')+(selected===n&&!used?' selected':'');el.textContent=n;if(!p){el.disabled=used||blocked||turn===1||ended;el.setAttribute('aria-pressed',String(selected===n));el.onclick=()=>{selected=n;removing=false;render()}}el.setAttribute('aria-label',`${n}, ${blocked?'für deinen nächsten Zug gesperrt':used?'bereits gesetzt':'verfügbar'}`);return el}))}
 $('remove').disabled=ended||turn===1||!rights[0]||!board.some(n=>n%2===1);$('remove').textContent=!rights[0]?'Entfernen verbraucht':removing?'Abbrechen':'Zahl entfernen · 1×';$('remove').setAttribute('aria-pressed',String(removing));$('ai-removal').textContent=rights[1]?'KI: Entfernen noch verfügbar':'KI: Entfernen verbraucht';$('last').textContent=last;$('choose').textContent=ended?'Runde beendet. Starte eine neue Runde.':removing?'Tippe auf eine violette Zahl. Entfernen zählt als dein Zug.':selected?`${selected} ausgewählt. Tippe auf ein freies Feld.`:locks[0]?`${locks[0]} ist diesen Zug gesperrt. Wähle eine andere Zahl oder entferne.`:'Zahl wählen, dann ein freies Feld antippen.';
 if(!ended){$('status').textContent=turn?'Die KI überlegt …':'Du bist dran';$('hint').textContent=turn?(moves(board,0,rights,locks).length?'Gleich bist du mit deinen geraden Zahlen dran.':'Du hast keinen gültigen Zug. Die KI ist nochmals dran.'):removing?'Wähle eine violette Zahl zum Entfernen.':selected?`Wohin möchtest du die ${selected} setzen?`:'Wähle eine Zahl oder nutze einmal Entfernen.';if(passNote)$('hint').textContent=passNote;else if(locks[0]&&turn===0)$('hint').textContent=`Deine ${locks[0]} ist diesen Zug gesperrt.`;$('turnsymbol').textContent=turn?'✦':'↳';$('turnsymbol').style.color=turn?'var(--purple)':'var(--lime)'}
}
function finish(p){winLines=winning(board);if(winLines.length){ended=true;$('status').textContent=p?'Die KI gewinnt.':'Du gewinnst!';$('hint').textContent=p?'Die letzte Zahl macht die 15 voll.':'Gut kombiniert. Deine letzte Zahl macht die 15 voll.';$('result').textContent=winLines.map(l=>l.map(i=>board[i]).join(' + ')+' = 15').join(' · ');$('result').hidden=false}else if(!board.includes(0)){ended=true;$('status').textContent='Unentschieden';$('hint').textContent='Alle Zahlen gesetzt. Keine Linie ergibt 15.';$('result').textContent='Neue Runde, neue Möglichkeiten.';$('result').hidden=false}if(ended)selected=null;return ended}
function apply(i,n,p,remove=false){const removed=board[i];const next=play(board,p,{i,n,remove},rights,locks);removing=false;latest=remove?-1:i;passNote='';if(p)last=remove?`Die KI hat deine ${removed} entfernt. Sie ist für deinen nächsten Zug gesperrt.`:`Letzter KI-Zug: ${n} · Zeile ${Math.floor(i/3)+1}, Spalte ${i%3+1}`;selected=null;if(!finish(p)){turn=next;if(next===p){passNote=p?'Du musstest aussetzen, weil kein gültiger Zug möglich war. Die KI ist nochmals dran.':'Die KI musste aussetzen. Du bist nochmals dran.';if(remove)last+=` ${1-p===0?'Dein':'Der KI-'} Aussetzzug hebt die Sperre auf.`;}}render()}
function removeHuman(i){if(ended||turn!==0||!rights[0]||!Number.isInteger(i)||i<0||i>8||board[i]%2!==1)throw new Error('Wähle eine gegnerische Zahl, wenn du am Zug bist.');apply(i,0,0,true);if(!ended&&turn===1)think();return state()}
function placeHuman(i,n){if(ended||turn!==0)throw new Error('Du bist gerade nicht am Zug.');if(!Number.isInteger(i)||i<0||i>8||board[i])throw new Error('Wähle ein freies Feld.');if(n===null){$('hint').textContent='Tippe zuerst unten auf eine deiner Zahlen.';$('human').querySelector('button:not(:disabled)')?.focus();return}if(!pool(0).includes(n)||board.includes(n)||locks[0]===n)throw new Error('Diese Zahl ist nicht verfügbar.');apply(i,n,0);if(!ended&&turn===1)think();return state()}
function accept(move,id){if(id!==round||ended||turn!==1)return;const legal=moves(board,1,rights,locks);const m=legal.find(m=>move&&m.i===move.i&&m.n===move.n&&!!m.remove===!!move.remove)||legal[0];if(m){apply(m.i,m.n,1,!!m.remove);if(!ended&&turn===1)think();}}
function think(){const id=round;clearTimeout(timer);timer=setTimeout(()=>{try{worker?.terminate();worker=new Worker('./worker-removal.js?v=lock1',{type:'module'});worker.onmessage=e=>accept(e.data.move,e.data.id);worker.onerror=()=>{worker?.terminate();accept(chooseMove(board,'medium',rights,locks),id)};worker.postMessage({board:[...board],level:$('difficulty').value,rights:[...rights],locks:[...locks],id})}catch{accept(chooseMove(board,'medium',rights,locks),id)}},550)}
function reset(){round++;clearTimeout(timer);worker?.terminate();board=Array(9).fill(0);rights=[true,true];locks=[null,null];passNote='';removing=false;turn=Number($('starter').value);selected=null;ended=false;winLines=[];latest=-1;last=turn?'Die KI überlegt ihren ersten Zug.':'Du eröffnest die Runde.';$('result').hidden=true;render();if(turn===1)think();return state()}
function state(){return {board:[...board],turn:ended?'finished':turn?'ai':'human',available:pool(0).filter(n=>!board.includes(n)&&locks[0]!==n),finished:ended,winningLines:winLines,removalAvailable:{human:rights[0],ai:rights[1]},blockedNumbers:{human:locks[0],ai:locks[1]}}}
$('remove').onclick=()=>{if(ended||turn!==0||!rights[0])return;removing=!removing;selected=null;render()};$('restart').onclick=reset;$('starter').onchange=reset;$('difficulty').onchange=()=>{if(turn===1&&!ended){round++;think()}};$('help').onclick=()=>$('rules').showModal();$('close').onclick=()=>$('rules').close();$('rules').addEventListener('click',e=>{if(e.target===$('rules')){const r=$('rules').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('rules').close()}});reset();
if(document.modelContext?.registerTool){const tools=[{name:'read_game',description:'Read the current game board and available human numbers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>state()},{name:'place_number',description:'Place an available even human number on an empty cell numbered 0–8; starts the AI reply.',inputSchema:{type:'object',properties:{cell:{type:'integer',minimum:0,maximum:8},number:{type:'integer',enum:[2,4,6,8]}},required:['cell','number'],additionalProperties:false},execute:input=>{if(!input||typeof input!=='object')throw new Error('Invalid input');return placeHuman(input.cell,input.number)}},{name:'remove_number',description:'Use the human once-per-round action to return an odd opponent number to its pool instead of placing a number.',inputSchema:{type:'object',properties:{cell:{type:'integer',minimum:0,maximum:8}},required:['cell'],additionalProperties:false},execute:input=>removeHuman(input.cell)},{name:'start_new_round',description:'Reset the current board and start a new round with the opening player selected in the interface.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>reset()}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}

