import {winning,pool,moves,chooseMove} from './engine.js';
const $=id=>document.getElementById(id);let board=Array(9).fill(0),turn=1,selected=null,ended=false,winLines=[],latest=-1,round=0,timer,worker;let last='Die KI überlegt ihren ersten Zug.';
function render(){
 $('board').replaceChildren(...board.map((n,i)=>{const el=document.createElement('button');el.className='cell'+(n?(n%2?' odd':' even'):'')+(winLines.some(l=>l.includes(i))?' win':'')+(latest===i?' latest':'');el.disabled=!!n||turn===1||ended;el.setAttribute('aria-label',`Zeile ${Math.floor(i/3)+1}, Spalte ${i%3+1}: ${n||'frei'}`);el.innerHTML=`<span class="position">${i+1}</span>${n||'·'}`;el.onclick=()=>placeHuman(i,selected);return el}));
 for(const [id,p]of [['human',0],['ai',1]]){$(id).replaceChildren(...pool(p).map(n=>{const used=board.includes(n),el=document.createElement(p?'span':'button');el.className='number'+(used?' used':'')+(selected===n&&!used?' selected':'');el.textContent=n;if(!p){el.disabled=used||turn===1||ended;el.setAttribute('aria-pressed',String(selected===n));el.onclick=()=>{selected=n;render()}}el.setAttribute('aria-label',`${n}, ${used?'bereits gesetzt':'verfügbar'}`);return el}))}
 $('last').textContent=last;$('choose').textContent=ended?'Runde beendet. Starte eine neue Runde.':selected?`${selected} ausgewählt. Tippe auf ein freies Feld.`:'Zahl wählen, dann ein freies Feld antippen.';
 if(!ended){$('status').textContent=turn?'Die KI überlegt …':'Du bist dran';$('hint').textContent=turn?(moves(board,0).length?'Gleich bist du mit deinen geraden Zahlen dran.':'Deine Zahlen sind gesetzt. Die KI setzt ihre letzte Zahl.'):selected?`Wohin möchtest du die ${selected} setzen?`:'Wähle eine deiner verfügbaren Zahlen.';$('turnsymbol').textContent=turn?'✦':'↳';$('turnsymbol').style.color=turn?'var(--purple)':'var(--lime)'}
}
function finish(p){winLines=winning(board);if(winLines.length){ended=true;$('status').textContent=p?'Die KI gewinnt.':'Du gewinnst!';$('hint').textContent=p?'Die letzte Zahl macht die 15 voll.':'Gut kombiniert. Deine letzte Zahl macht die 15 voll.';$('result').textContent=winLines.map(l=>l.map(i=>board[i]).join(' + ')+' = 15').join(' · ');$('result').hidden=false}else if(!board.includes(0)){ended=true;$('status').textContent='Unentschieden';$('hint').textContent='Alle Zahlen gesetzt. Keine Linie ergibt 15.';$('result').textContent='Neue Runde, neue Möglichkeiten.';$('result').hidden=false}if(ended)selected=null;return ended}
function apply(i,n,p){board[i]=n;latest=i;if(p)last=`Letzter KI-Zug: ${n} · Zeile ${Math.floor(i/3)+1}, Spalte ${i%3+1}`;selected=null;if(!finish(p)){turn=moves(board,1-p).length?1-p:p;}render()}
function placeHuman(i,n){if(ended||turn!==0)throw new Error('Du bist gerade nicht am Zug.');if(!Number.isInteger(i)||i<0||i>8||board[i])throw new Error('Wähle ein freies Feld.');if(n===null){$('hint').textContent='Tippe zuerst unten auf eine deiner Zahlen.';$('human').querySelector('button:not(:disabled)')?.focus();return}if(!pool(0).includes(n)||board.includes(n))throw new Error('Diese Zahl ist nicht verfügbar.');apply(i,n,0);if(!ended)think();return state()}
function accept(move,id){if(id!==round||ended||turn!==1)return;const valid=move&&Number.isInteger(move.i)&&move.i>=0&&move.i<9&&!board[move.i]&&pool(1).includes(move.n)&&!board.includes(move.n);const m=valid?move:moves(board,1)[0];if(m){apply(m.i,m.n,1);if(!ended&&turn===1)think();}}
function think(){const id=round;clearTimeout(timer);timer=setTimeout(()=>{try{worker?.terminate();worker=new Worker('./worker.js',{type:'module'});worker.onmessage=e=>accept(e.data.move,e.data.id);worker.onerror=()=>{worker?.terminate();accept(chooseMove(board,'medium'),id)};worker.postMessage({board:[...board],level:$('difficulty').value,id})}catch{accept(chooseMove(board,'medium'),id)}},550)}
function reset(){round++;clearTimeout(timer);worker?.terminate();board=Array(9).fill(0);turn=Number($('starter').value);selected=null;ended=false;winLines=[];latest=-1;last=turn?'Die KI überlegt ihren ersten Zug.':'Du eröffnest die Runde.';$('result').hidden=true;render();if(turn===1)think();return state()}
function state(){return {board:[...board],turn:ended?'finished':turn?'ai':'human',available:pool(0).filter(n=>!board.includes(n)),finished:ended,winningLines:winLines}}
$('restart').onclick=reset;$('starter').onchange=reset;$('difficulty').onchange=()=>{if(turn===1&&!ended){round++;think()}};$('help').onclick=()=>$('rules').showModal();$('close').onclick=()=>$('rules').close();$('rules').addEventListener('click',e=>{if(e.target===$('rules')){const r=$('rules').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('rules').close()}});reset();
if(document.modelContext?.registerTool){const tools=[{name:'read_game',description:'Read the current game board and available human numbers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>state()},{name:'place_number',description:'Place an available even human number on an empty cell numbered 0–8; starts the AI reply.',inputSchema:{type:'object',properties:{cell:{type:'integer',minimum:0,maximum:8},number:{type:'integer',enum:[2,4,6,8]}},required:['cell','number'],additionalProperties:false},execute:input=>{if(!input||typeof input!=='object')throw new Error('Invalid input');return placeHuman(input.cell,input.number)}},{name:'start_new_round',description:'Reset the current board and start a new round with the opening player selected in the interface.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>reset()}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
